#!/usr/bin/env bash
mkdir -p ./bin
javac -d ./bin -sourcepath src/main/java/ src/main/java/mega/cosmos/app/ClassMatcher.java src/main/java/mega/cosmos/app/ClassFinder.java src/main/java/mega/cosmos/app/SplitUtils.java
java -cp ./bin mega.cosmos.app.ClassFinder "$@"
rm -rf ./bin